spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/sns
  username: ${{secrets.DB_USERNAME}}
  password: ${{secrets.DB_PASSWORD}}
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: ${{secrets.JWT_SECRET_KEY}}
  token.expired-time-ms: ${{secrets.JWT_EXPIRED_TIME_MS}} # 30 days