spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/sns
  username: username
  password: password
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: secret-key
  token.expired-time-ms: expired-time-ms # 30 days